//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLMS0._1
{
    using System;
    using System.Collections.Generic;
    
    public partial class reg_user
    {
        public int reg_id { get; set; }
        public string reg_uname { get; set; }
        public string reg_pass { get; set; }
        public string reg_cpass { get; set; }
        public string email_id { get; set; }
        public decimal mobile_no { get; set; }
    }
}
