//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLM0._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class acc_item_type
    {
        public int acc_id { get; set; }
        public int item_id { get; set; }
        public int type_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual mor_item mor_item { get; set; }
        public virtual mor_type mor_type { get; set; }
    }
}
