//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLM0._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.accounts = new HashSet<account>();
        }
    
        public int c_id { get; set; }
        public string c_fname { get; set; }
        public string c_mname { get; set; }
        public string c_lname { get; set; }
        public string address { get; set; }
        public decimal age { get; set; }
        public decimal mobile_no { get; set; }
        public string city { get; set; }
        public Nullable<decimal> pin_no { get; set; }
        public string email_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account> accounts { get; set; }
    }
}
