//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MLM0._0
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mlms_DBEntities2 : DbContext
    {
        public mlms_DBEntities2()
            : base("name=mlms_DBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<log_user> log_user { get; set; }
        public virtual DbSet<mor_item> mor_item { get; set; }
        public virtual DbSet<mor_type> mor_type { get; set; }
        public virtual DbSet<reference> references { get; set; }
        public virtual DbSet<reg_user> reg_user { get; set; }
        public virtual DbSet<transection> transections { get; set; }
        public virtual DbSet<acc_item_type> acc_item_type { get; set; }
        public virtual DbSet<cash> cashes { get; set; }
        public virtual DbSet<cheque> cheques { get; set; }
    }
}
