//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authwebpart
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public int acc_id { get; set; }
        public string acc_no { get; set; }
        public int acc_bal { get; set; }
        public System.DateTime acc_date { get; set; }
    }
}
